spring:
  main:
    allow-circular-references: true
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: 'org.h2.Driver'
    username: 'username'
    password: 'password'
  jpa:
      hibernate.ddl-auto: 'none'
      database-platform: 'org.hibernate.dialect.H2Dialect'
      h2.console.enabled: 'true'

jwt:
  secret: 'diSqm4a81QwE9z3255CFHMcQfTjfoo09barWnZ123r4u788x1AcDdsGKaNdRgUkXp2iogi26hvbmad21'
  validity: 3600